### ISSUE TITLE
Blockwise coregistration fails with large data gaps

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#185]
If certain blocks (or chunks) created by the blockwise coregistration include only NaNs, the function fails with error:
> ValueError: Fitting failed for XX chunks:

Instead, the empty chunks should be ignored.

This is useful in many cases, as most DEMs footprint is rotated compared to the geographic grid, creating large gaps around the DEM (see illustration below).

A way to reproduce is to modify the script in the example at this line: https://github.com/GlacioHack/xdem/blob/2fb86d85ad9cf5a7476013f55a38aa9a38c7b422/examples/plot_blockwise_coreg.py#L33
Add:
```
reference_dem = reference_dem.reproject(dst_crs='EPSG:3413', dst_res=reference_dem.res, resampling='bilinear')
dem_to_be_aligned = dem_to_be_aligned.reproject(dst_ref=reference_dem, resampling='bilinear')
```
This will create a nicely rotated DEM with lots of gaps :smile:

![Figure_1](https://user-images.githubusercontent.com/3285905/124951913-13bc3000-e014-11eb-9994-182e46928cfb.png)

**Comment by erikmannerfelt** [comment]
Oh, that's not right! I made this specifically to be okay with nans, but as is tradition here in xdem, I didn't properly test it ;)

**Comment by adehecq** [comment]
PR #64 should be on top of our priority list !!

**Comment by erikmannerfelt** [comment]
Oh wait, I think you misunderstood the error (rightfully so, because it's not super descriptive). Upon instantiation, you can set the `success_threshold`, whereby it will count the number of succeeded blocks and then determine if that error should occur.

Arguably, however, it would be nice to skip completely empty blocks, and not include that in the `success_threshold` calculation...

**Comment by adehecq** [comment]
Aaaah, good to know! But yes, maybe completely empty blocks could be excluded from the count...
