### ISSUE TITLE
Delete the sample data sets from git history

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#31]

**Comment by erikmannerfelt** [comment]
This can be done with [bfg](https://rtyley.github.io/bfg-repo-cleaner/) (basically a cleaner version of pure git code):

```bash
bfg --strip-blobs-bigger-than 3M
```
This will remove all the examples, but will keep the ipynb's that are larger since they still exist in the most recent commit.

This cannot be made as a normal PR as I understand, since it modifies the entire history. I therefore suggest to do this once everyone's ready when we don't have any active PRs.
