### ISSUE TITLE
[Enhancement] A new coreg

### ISSUE THREAD

**Issue by liuh886** [GlacioHack/xdem#335]
Hi, @rhugonnet 

I recently developed a new Coreg method, which supports ICESat-2 point-DEM coregistration, and also does pretty well on DEM coregistration. Now,[ in this branch xDEM](https://github.com/liuh886/xdem_snow/tree/xsnow) can also run this method as well! Here is [a quick review of the function and results](https://github.com/liuh886/xdem_snow/blob/xsnow/Zhihao_test_on_new_coreg.ipynb
):

The new method is a significant improvement over previous methods like NuthKaab. I am seeking help to test and stabilize the method before submitting it as a pull request to share the code with others.

**Comment by adehecq** [comment]
Hi @liuh886,
It's great that you are able to contribute to xdem. I'm looking forward to check and test your new algorithm.
I saw that you opened a PR and then closed it. Actually you can set the PR as "draft" rather than closing it. This way people know that it's still work in progress but can have a look at the changes.
