### ISSUE TITLE
DEM changing of geoid not working

### ISSUE THREAD

**Issue by LucBeraud** [GlacioHack/xdem#344]
The function _xdem.DEM.set_vref()_ does not seems to perfectly set the ccrs with my data. Or, _.to_vref()_ should not use the ccrs created by _.set_vref()_?

**To reproduce it:**
[GLO90_sub.tif.zip](https://github.com/GlacioHack/xdem/files/11027505/GLO90_sub.tif.zip)
#First, unzip the DEM .tif file in the attached archive, 
`import xdem`
`mnt = xdem.DEM(PathToDEM) # path of the .tif`
`mnt.set_vref('EGM08')`
`mnt.ccrs # prints +geoidgrids is set with EGM08, but ellipsoid is set to WGS84`
`print(mnt.data)`
`mnt.to_vref('WGS84')`
`print(mnt.data) # no elevation change noticed`

In the example, we set the geoid to EGM08 and ask to transform it to WGS84 ellipsoid.
The _mnt.ccrs_ prints ellipsoid WGS84 (not the geoid EGM08), and _to_ref()_ uses the _.ccrs_ attribute and not the _vref_ value (which indeed is EGM08), so no transformation is done.

OS: Ubuntu 22
Environment : xdem (0.0.7) from the repository

**Comment by LucBeraud** [comment]
Hello, here it is !
[env_list_Luc.txt](https://github.com/GlacioHack/xdem/files/11050875/env_list_Luc.txt)

I get this for your code : `RasterioIOError: /home/beraudlu/miniconda3/envs/xdem/share/proj/us_nga_egm08_25.tif: No such file or directory`

**Comment by adehecq** [comment]
Found the issue ! You don't have proj-data installed. Run `conda install -c conda-forge proj-data`.
It's listed in the dependencies in `environment.yml` so the issue must have occurred when you installed xdem from the github repo.

**Comment by adehecq** [comment]
What need to be modified in xdem is [here](https://github.com/GlacioHack/xdem/blob/f40e897761704bffe5ad54ff6b43e3db0730a6f1/xdem/dem.py#L190). The condition to check that the file exist should be outside of the else block.

**Comment by LucBeraud** [comment]
Thanks, I now have the good plot !
But my `to_vref()` still does not change the data.

**Comment by adehecq** [comment]
Ok, I tried updating my pyproj version to match yours. I can reproduce your error with pyproj=3.4.0 (and 3.4.1) but it works fine with pyproj=3.3.1.
Maybe something changed in the new version.

**Comment by LucBeraud** [comment]
Yep it works fine with pyproj=3.3.1 for me too, now. Thanks !

**Comment by adehecq** [comment]
I have investigated to try to figure out what differs between the two versions of pyproj without success...
In either case, `ccrs_init` and `ccrs_dest` defined in the method [to_vref](https://github.com/GlacioHack/xdem/blob/f40e897761704bffe5ad54ff6b43e3db0730a6f1/xdem/dem.py#L221) are identical. Even `ccrs_init.datum` and `ccrs_dest.datum` are the same. I could not find anything about what pyproj does when initializing a CRS with the option "geoidgrids"...

**Comment by rhugonnet** [comment]
Yes, `geoidgrids` was an argument on in its way to be deprecated I think :cry:.

Maybe we need to build the compound CRS ourselves now, I'll have a closer look next week!

**Comment by rhugonnet** [comment]
Ongoing in #350

> In either case, ccrs_init and ccrs_dest defined in the method [to_vref](https://github.com/GlacioHack/xdem/blob/f40e897761704bffe5ad54ff6b43e3db0730a6f1/xdem/dem.py#L221) are identical.

Actually `ccrs_dest` was being updated by a property call of `vref`, so the `to_vref()` function was behaving correctly (but poorly written, interesting to see the progress made on that side in 2.5 years!). 

The reason it stopped working is because `pyproj`/`PROJ` now only transform the `z` coordinate if both input and output `CRS` are 3D. This is fairly new, which explains why everything still works on older `pyproj` versions. For instance, classic WGS84 `CRS("EPSG:4326")` does not work now, instead one needs to pass the 3D version of it `CRS("EPSG:4979")` (https://epsg.io/4979). See for example: https://gis.stackexchange.com/questions/436401/transforming-epsg4979-to-given-wkt-epsg6654, and several other issues in `pyproj`.

In addition to adapting to that new behaviour, I reworked the entire vertical CRS framework of `xdem.DEM` to be more robust and easy-to-use. However, I'm running into some issues to consistently cast the `CRS` back to 2D when they are already 3D and I need to create a `CompoundCRS` with a vertical CRS. 

I opened a discussion in `pyproj`:  https://github.com/pyproj4/pyproj/discussions/1265

**Comment by rhugonnet** [comment]
Actually, a good summary of that new behaviour is shown here: https://pyproj4.github.io/pyproj/stable/advanced_examples.html#promote-crs-to-3d

Update on the issue: I just added `CRS.to_2d()` to `pyproj` (simply needed to be wrapped from `PROJ` where it already existed). It will take some time until there's a new release and we can use that function in xDEM, so I'll finalize the PR with a `NotImplemented` error in the meantime :slightly_smiling_face:  (which will only apply to the case a CRS passed is 3D and need to be re-cast to 2D).
