### ISSUE TITLE
Coreg inheritance diagram not rendering on RTD

### ISSUE THREAD

**Issue by dshean** [GlacioHack/xdem#359]
I briefly looked at source for a fix, but not sure whether issue is coming from eval-rst, sphinx, or rtd.

https://xdem.readthedocs.io/en/latest/coregistration.html#the-coreg-object
https://github.com/GlacioHack/xdem/blob/main/doc/source/coregistration.md#the-classxdemcoreg-object

<img width="708" alt="Coregistration — xDEM 2023-04-21 10-40-33" src="https://user-images.githubusercontent.com/1103530/233700557-38827f53-4d22-4a2b-8f09-f7d99595a323.png">

**Comment by rhugonnet** [comment]
Good catch! 
Unfortunately I've seen this one before :cry:: it's because the inheritance diagram needs to run `graphviz.dot`.
Here's the build error: 
`WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting`

Adding `graphviz` as a dependency to the `dev-environment.yml` works, but is a bit of a nightmare as it sometimes breaks the environment solve during CI (even with `mamba`).
Strangely, the diagrams were working for a while even without `graphviz` and only started breaking recently, any idea on this @erikmannerfelt?
